import { StyleSheet } from 'react-native';
import colors from '../../../constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  backButton: {
    padding: 4,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
    fontStyle: 'normal',
  },
  customerInfoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    padding: 16,
    margin: 20,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  customerAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.brand,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  customerInitials: {
    color: '#fff',
    fontSize: 16,
  },
  customerDetails: {
    flex: 1,
  },
  customerNameLabel: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 8,
  },
  customerNameInput: {
    fontSize: 16,
    color: '#1f2937',
    paddingVertical: 8,
    paddingHorizontal: 0,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  customerNameText: {
    fontSize: 16,
    color: '#1f2937',
    marginBottom: 2,
  },
  customerPhone: {
    fontSize: 14,
    color: '#6b7280',
  },
  selectOutfitTitle: {
    fontSize: 18,
    color: '#1f2937',
    marginHorizontal: 20,
    marginBottom: 16,
  },
  outfitSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 20,
    marginBottom: 16,
    paddingHorizontal: 16,
    height: 48,
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  outfitSearchInput: {
    flex: 1,
    fontSize: 16,
    color: '#1f2937',
  },
  searchIcon: {
    marginRight: 8,
  },
  genderFilter: {
    flexDirection: 'row',
    padding: 6,
    marginHorizontal: 20,
    marginBottom: 20,
    backgroundColor: '#f3f4f6',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    gap: 4,
  },
  genderButton: {
    flex: 1,
    borderRadius: 8,
    marginHorizontal: 2,
  },
  genderButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6b7280',
  },
  genderButtonTextActive: {
    color: '#ffffff',
    fontWeight: '700',
  },
  outfitGrid: {
    paddingHorizontal: 16,
    paddingBottom: 20,
  },
  outfitRow: {
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  outfitGridItem: {
    flex: 1,
    margin: 4,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    minHeight: 100,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  outfitGridIconContainer: {
    width: 50,
    height: 50,
    backgroundColor: 'transparent',
    borderRadius: 0,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    borderWidth: 0,
    borderColor: 'transparent',
  },
  outfitGridName: {
    fontSize: 11,
    color: '#1f2937',
    textAlign: 'center',
    lineHeight: 14,
    fontWeight: '500',
  },
});
